[phases.setup]
aptPkgs = [
    "ffmpeg",
    "libcairo2-dev",
    "libpango1.0-dev",
    "pkg-config",
    "libglib2.0-0",
    "libgl1",
    "libsm6",
    "libxext6",
    "libxrender1"
]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"
